package com.bbu.shop.search.pojo.po;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cat_id
     *
     * @mbggenerated
     */
    private Integer cat_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cat_name
     *
     * @mbggenerated
     */
    private String cat_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cat_id
     *
     * @return the value of category.cat_id
     *
     * @mbggenerated
     */
    public Integer getCat_id() {
        return cat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cat_id
     *
     * @param cat_id the value for category.cat_id
     *
     * @mbggenerated
     */
    public void setCat_id(Integer cat_id) {
        this.cat_id = cat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cat_name
     *
     * @return the value of category.cat_name
     *
     * @mbggenerated
     */
    public String getCat_name() {
        return cat_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cat_name
     *
     * @param cat_name the value for category.cat_name
     *
     * @mbggenerated
     */
    public void setCat_name(String cat_name) {
        this.cat_name = cat_name == null ? null : cat_name.trim();
    }
}