package com.bbu.shop.search.pojo.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPro_idIsNull() {
            addCriterion("pro_id is null");
            return (Criteria) this;
        }

        public Criteria andPro_idIsNotNull() {
            addCriterion("pro_id is not null");
            return (Criteria) this;
        }

        public Criteria andPro_idEqualTo(Integer value) {
            addCriterion("pro_id =", value, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idNotEqualTo(Integer value) {
            addCriterion("pro_id <>", value, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idGreaterThan(Integer value) {
            addCriterion("pro_id >", value, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("pro_id >=", value, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idLessThan(Integer value) {
            addCriterion("pro_id <", value, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idLessThanOrEqualTo(Integer value) {
            addCriterion("pro_id <=", value, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idIn(List<Integer> values) {
            addCriterion("pro_id in", values, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idNotIn(List<Integer> values) {
            addCriterion("pro_id not in", values, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idBetween(Integer value1, Integer value2) {
            addCriterion("pro_id between", value1, value2, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_idNotBetween(Integer value1, Integer value2) {
            addCriterion("pro_id not between", value1, value2, "pro_id");
            return (Criteria) this;
        }

        public Criteria andPro_nameIsNull() {
            addCriterion("pro_name is null");
            return (Criteria) this;
        }

        public Criteria andPro_nameIsNotNull() {
            addCriterion("pro_name is not null");
            return (Criteria) this;
        }

        public Criteria andPro_nameEqualTo(String value) {
            addCriterion("pro_name =", value, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameNotEqualTo(String value) {
            addCriterion("pro_name <>", value, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameGreaterThan(String value) {
            addCriterion("pro_name >", value, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameGreaterThanOrEqualTo(String value) {
            addCriterion("pro_name >=", value, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameLessThan(String value) {
            addCriterion("pro_name <", value, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameLessThanOrEqualTo(String value) {
            addCriterion("pro_name <=", value, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameLike(String value) {
            addCriterion("pro_name like", value, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameNotLike(String value) {
            addCriterion("pro_name not like", value, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameIn(List<String> values) {
            addCriterion("pro_name in", values, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameNotIn(List<String> values) {
            addCriterion("pro_name not in", values, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameBetween(String value1, String value2) {
            addCriterion("pro_name between", value1, value2, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_nameNotBetween(String value1, String value2) {
            addCriterion("pro_name not between", value1, value2, "pro_name");
            return (Criteria) this;
        }

        public Criteria andPro_priceIsNull() {
            addCriterion("pro_price is null");
            return (Criteria) this;
        }

        public Criteria andPro_priceIsNotNull() {
            addCriterion("pro_price is not null");
            return (Criteria) this;
        }

        public Criteria andPro_priceEqualTo(Double value) {
            addCriterion("pro_price =", value, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceNotEqualTo(Double value) {
            addCriterion("pro_price <>", value, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceGreaterThan(Double value) {
            addCriterion("pro_price >", value, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceGreaterThanOrEqualTo(Double value) {
            addCriterion("pro_price >=", value, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceLessThan(Double value) {
            addCriterion("pro_price <", value, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceLessThanOrEqualTo(Double value) {
            addCriterion("pro_price <=", value, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceIn(List<Double> values) {
            addCriterion("pro_price in", values, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceNotIn(List<Double> values) {
            addCriterion("pro_price not in", values, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceBetween(Double value1, Double value2) {
            addCriterion("pro_price between", value1, value2, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_priceNotBetween(Double value1, Double value2) {
            addCriterion("pro_price not between", value1, value2, "pro_price");
            return (Criteria) this;
        }

        public Criteria andPro_imageIsNull() {
            addCriterion("pro_image is null");
            return (Criteria) this;
        }

        public Criteria andPro_imageIsNotNull() {
            addCriterion("pro_image is not null");
            return (Criteria) this;
        }

        public Criteria andPro_imageEqualTo(String value) {
            addCriterion("pro_image =", value, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageNotEqualTo(String value) {
            addCriterion("pro_image <>", value, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageGreaterThan(String value) {
            addCriterion("pro_image >", value, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageGreaterThanOrEqualTo(String value) {
            addCriterion("pro_image >=", value, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageLessThan(String value) {
            addCriterion("pro_image <", value, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageLessThanOrEqualTo(String value) {
            addCriterion("pro_image <=", value, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageLike(String value) {
            addCriterion("pro_image like", value, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageNotLike(String value) {
            addCriterion("pro_image not like", value, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageIn(List<String> values) {
            addCriterion("pro_image in", values, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageNotIn(List<String> values) {
            addCriterion("pro_image not in", values, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageBetween(String value1, String value2) {
            addCriterion("pro_image between", value1, value2, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_imageNotBetween(String value1, String value2) {
            addCriterion("pro_image not between", value1, value2, "pro_image");
            return (Criteria) this;
        }

        public Criteria andPro_descIsNull() {
            addCriterion("pro_desc is null");
            return (Criteria) this;
        }

        public Criteria andPro_descIsNotNull() {
            addCriterion("pro_desc is not null");
            return (Criteria) this;
        }

        public Criteria andPro_descEqualTo(String value) {
            addCriterion("pro_desc =", value, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descNotEqualTo(String value) {
            addCriterion("pro_desc <>", value, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descGreaterThan(String value) {
            addCriterion("pro_desc >", value, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descGreaterThanOrEqualTo(String value) {
            addCriterion("pro_desc >=", value, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descLessThan(String value) {
            addCriterion("pro_desc <", value, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descLessThanOrEqualTo(String value) {
            addCriterion("pro_desc <=", value, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descLike(String value) {
            addCriterion("pro_desc like", value, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descNotLike(String value) {
            addCriterion("pro_desc not like", value, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descIn(List<String> values) {
            addCriterion("pro_desc in", values, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descNotIn(List<String> values) {
            addCriterion("pro_desc not in", values, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descBetween(String value1, String value2) {
            addCriterion("pro_desc between", value1, value2, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_descNotBetween(String value1, String value2) {
            addCriterion("pro_desc not between", value1, value2, "pro_desc");
            return (Criteria) this;
        }

        public Criteria andPro_dateIsNull() {
            addCriterion("pro_date is null");
            return (Criteria) this;
        }

        public Criteria andPro_dateIsNotNull() {
            addCriterion("pro_date is not null");
            return (Criteria) this;
        }

        public Criteria andPro_dateEqualTo(Date value) {
            addCriterionForJDBCDate("pro_date =", value, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("pro_date <>", value, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("pro_date >", value, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pro_date >=", value, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateLessThan(Date value) {
            addCriterionForJDBCDate("pro_date <", value, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pro_date <=", value, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateIn(List<Date> values) {
            addCriterionForJDBCDate("pro_date in", values, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("pro_date not in", values, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pro_date between", value1, value2, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pro_date not between", value1, value2, "pro_date");
            return (Criteria) this;
        }

        public Criteria andPro_statusIsNull() {
            addCriterion("pro_status is null");
            return (Criteria) this;
        }

        public Criteria andPro_statusIsNotNull() {
            addCriterion("pro_status is not null");
            return (Criteria) this;
        }

        public Criteria andPro_statusEqualTo(Integer value) {
            addCriterion("pro_status =", value, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusNotEqualTo(Integer value) {
            addCriterion("pro_status <>", value, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusGreaterThan(Integer value) {
            addCriterion("pro_status >", value, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("pro_status >=", value, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusLessThan(Integer value) {
            addCriterion("pro_status <", value, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusLessThanOrEqualTo(Integer value) {
            addCriterion("pro_status <=", value, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusIn(List<Integer> values) {
            addCriterion("pro_status in", values, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusNotIn(List<Integer> values) {
            addCriterion("pro_status not in", values, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusBetween(Integer value1, Integer value2) {
            addCriterion("pro_status between", value1, value2, "pro_status");
            return (Criteria) this;
        }

        public Criteria andPro_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("pro_status not between", value1, value2, "pro_status");
            return (Criteria) this;
        }

        public Criteria andCat_idIsNull() {
            addCriterion("cat_id is null");
            return (Criteria) this;
        }

        public Criteria andCat_idIsNotNull() {
            addCriterion("cat_id is not null");
            return (Criteria) this;
        }

        public Criteria andCat_idEqualTo(Integer value) {
            addCriterion("cat_id =", value, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idNotEqualTo(Integer value) {
            addCriterion("cat_id <>", value, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idGreaterThan(Integer value) {
            addCriterion("cat_id >", value, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("cat_id >=", value, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idLessThan(Integer value) {
            addCriterion("cat_id <", value, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idLessThanOrEqualTo(Integer value) {
            addCriterion("cat_id <=", value, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idIn(List<Integer> values) {
            addCriterion("cat_id in", values, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idNotIn(List<Integer> values) {
            addCriterion("cat_id not in", values, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idBetween(Integer value1, Integer value2) {
            addCriterion("cat_id between", value1, value2, "cat_id");
            return (Criteria) this;
        }

        public Criteria andCat_idNotBetween(Integer value1, Integer value2) {
            addCriterion("cat_id not between", value1, value2, "cat_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}